### ISSUE TITLE
Day 43 Lab - Missing technical requirement

### ISSUE THREAD

**Issue by elaewin** [luayyounus/Cross-platformTodoList#13]
You are still missing the following technical requirement:

* When your `TVOS` application first launches, before loading `Todos` into the `tableView`, you should prompt the user for their email, and populate the `UITableView` with only their associated `Todos`.

When I enter an email in the app and select go, I get the following message in the console:  
`2017-05-12 11:43:06.903 TV-TodoList[28940:14401417] Not FOUND`

**Comment by luyounus** [comment]
Fixed the issue. Thank you Erica!
