### ISSUE TITLE
Day 41 Lab - Missing Technical Requirements

### ISSUE THREAD

**Issue by elaewin** [luayyounus/Cross-platformTodoList#3]
* Using `Firebase Auth`, implement a `LoginViewController` to handle the `login` logic for your application.  
	* *When the application first launches, it should check if there is currently a user logged in.*  
	* *If the user enters wrong credentials, or has not created an account, they should be presented with an appropriate alert prompting them to try again or sign up.* - **Note:** unable to test, because this caused the app to crash.  
* Implement a `Log Out` button, to `logout` the current user when pressed.   
* Implement a `+` button as the NavigationItem's **Right** barButtonItem that animates the container view open/closed.  
	* The architecture of this is up to you but a simple implementation would be to animate the containerView's height constraint.  
* In `HomeViewController` implement fetching `Todo` items from `Firebase` and setup listening for updates to the `Database` JSON.  **Note:** unable to test.
* Upon creating a new `Todo` in your `NewTodoViewController`, upload the new `Todo` item to the `Firebase Database`.  
	* This should for the `HomeViewController` to be notified of the updates to the database JSON and update the `UITableView` to reflect the new `Todo`.

**Comment by luyounus** [comment]
Done
