### ISSUE TITLE
Day 42 Lab - Missing technical requirements

### ISSUE THREAD

**Issue by elaewin** [luayyounus/Cross-platformTodoList#5]
You are still missing the following technical requirements:

* Implement a new `UIViewController` subclass that displays completed Todo's on the new tab of the `UITabBarController`. This will be more challenging then it seems since we will need to make updates to our `Todo` model as well as the Firebase Database. Also, Booleans are not supported so, if going in this direction, you will need to use a NSNumber value of `1` or `0` to represent a completed Todo in the Firebase Database.  
* Implement the ability to **Delete or Complete** a Todo Item from the iOS application.

**Comment by luyounus** [comment]
Fixed.
